// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChRIG-r_J66nXryTpvbcllRTq7mzUTnQI',
    appId: '1:989785979082:web:bcbeaab61baf9a6f40dc33',
    messagingSenderId: '989785979082',
    projectId: 'flutter-firebase-app-1921a',
    authDomain: 'flutter-firebase-app-1921a.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-app-1921a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-app-1921a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOmJfM3q4lsKCS0c3fw3sy5dPMH-2Xlc',
    appId: '1:989785979082:android:b2dbf4e263a18b0640dc33',
    messagingSenderId: '989785979082',
    projectId: 'flutter-firebase-app-1921a',
    databaseURL: 'https://flutter-firebase-app-1921a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-app-1921a.appspot.com',
  );
}
